kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "nfs-provisioner.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nfs-provisioner.name" . }}
     # replace with namespace where provisioner is deployed
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "nfs-provisioner.name" . }}
  apiGroup: rbac.authorization.k8s.io
