kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: leader-locking-{{ include "nfs-provisioner.name" . }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nfs-provisioner.name" . }}
    # replace with namespace where provisioner is deployed
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: leader-locking-{{ include "nfs-provisioner.name" . }}
  apiGroup: rbac.authorization.k8s.io

